# Generated by Django 3.1.6 on 2021-03-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
